# Generated by Django 5.2 on 2025-04-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
